/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GhepChuongTrinh;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class QLHD_Panel extends javax.swing.JPanel {

    /**
     * Creates new form QLHD_Panel
     */
    public QLHD_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThanhTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayDat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQLDH = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtTrangThai = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        txtThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhTienActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã ĐH");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên SP");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Tên KH");

        txtMaDH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Ngày đặt");

        txtTenSP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Trạng thái");

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Thành tiền");

        txtNgayDat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNgayDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDatActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbQLDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐH", "TênKH", "Tên SP", "Ngày đặt", "Trạng thái", "Thành tiền"
            }
        ));
        tbQLDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQLDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQLDH);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtTrangThai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtNgayDat)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhTienActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtNgayDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ConnectMySQL con = new ConnectMySQL();
            if(txtMaDH.getText().equals("") || txtTenKH.getText().equals("") ||
                txtTenSP.getText().equals("") ||txtTrangThai.getText().equals("") ||
                txtNgayDat.getText().equals("") ||txtThanhTien.getText().equals("") ){
                JOptionPane.showMessageDialog(this, "bạn cần nhập đầy đủ thông tin");
                //nếu ng dùng nhập không đầy đủ thông tin thì báo nhập thiếu
            } else{//nếu nhập đầy đủ thì thực thi hành động
                //bẫy lỗi trùng khóa chính mã ĐH nếu nhập vào đh mà trên db đẫ tồn tại
                StringBuffer sb = new StringBuffer();
                ResultSet rs = con.getdata1(txtMaDH.getText());
                if(rs.next()){
                    sb.append("Đơn hàng này đã tồn tại");
                }
                if(sb.length()>0){//nếu rs trả về kết quá thì if trên đúng, nên báo đơn hàng này đã tồn tại
                    JOptionPane.showMessageDialog(this, sb.toString());
                }
                else //ngược lại nếu đơn hàng chưa tồn tại thì thêm mới
                {
                    String sql = "insert into hoadon values('"+txtMaDH.getText()+"'"
                    + ",'"+txtTenKH.getText()+"','"+txtTenSP.getText()+"'"
                    + ",'"+txtNgayDat.getText()+"','"+txtTrangThai.getText()+"','"+txtThanhTien.getText()+"',"
                    + "'','','','')";
                    Statement st = con.conn.createStatement();
                    st = con.conn.createStatement();
                    int kq = st.executeUpdate(sql);
                    if(kq>0)
                    {
                        JOptionPane.showMessageDialog(this, "thêm mới thành công");
                        xoaTextField();
                    }
                }
            }
            con.close();

        } catch(ClassNotFoundException ex){
            ex.printStackTrace();
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbQLDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQLDHMouseClicked
        int x = tbQLDH.getSelectedRow();
        if(x>=0){
            txtMaDH.setText(tbQLDH.getValueAt(x, 0)+"");
            txtTenKH.setText(tbQLDH.getValueAt(x, 1)+"");
            txtTenSP.setText(tbQLDH.getValueAt(x, 2)+"");
            txtNgayDat.setText(tbQLDH.getValueAt(x, 3)+"");
            txtTrangThai.setText(tbQLDH.getValueAt(x, 4)+"");
            txtThanhTien.setText(tbQLDH.getValueAt(x, 5)+"");
            //txtMaDH.setEnabled(false);
        }
    }//GEN-LAST:event_tbQLDHMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            ConnectMySQL con = new ConnectMySQL();
            StringBuffer sb = new StringBuffer();
            ResultSet rs = con.getdata1(txtMaDH.getText());
            if(rs.next()){
                sb.append("Đơn hàng này đã tồn tại");
            }
            if(sb.length()>0){//nếu rs trả về kết quá thì if trên đúng, nên báo đơn hàng này đã tồn tại
                JOptionPane.showMessageDialog(this, sb.toString());
            }
            else //ngược lại nếu đơn hàng chưa tồn tại thì thêm mới
            {
                String sql = "update hoadon set TenKH = '"+txtTenKH.getText()+"', TenSP = '"+txtTenSP.getText()+"'"
                + ",NgayDat = '"+txtNgayDat.getText()+"',TrangThai = '"+txtTrangThai.getText()+"',ThanhTien = '"+txtThanhTien.getText()+"'"
                + "where MaHD = '"+txtMaDH.getText()+"'";
                Statement st= con.conn.createStatement();
                int kq = st.executeUpdate(sql);
                if(kq>0){
                    JOptionPane.showMessageDialog(this, "Sửa thành công ");
                    xoaTextField();
                }
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        xoatrangtable();
        try {
            ConnectMySQL con = new ConnectMySQL();
            String sql = "Delete from hoadon where MaHD = '"+txtMaDH.getText()+"'";
            Statement st = con.conn.createStatement();
            int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa chứ ?", "thông báo!", JOptionPane.YES_NO_OPTION);
            if(check== JOptionPane.YES_OPTION)
            {
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                xoaTextField();
            }
            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        xoaTextField();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        xoatrangtable();
        try {
            ConnectMySQL con = new ConnectMySQL();
            ResultSet rs = con.getdata2(txtSearch.getText());
            int i = 0;
            while(rs.next()){
                tbQLDH.setValueAt(rs.getString("MaHD"), i, 0);
                tbQLDH.setValueAt(rs.getString("TenKH"), i, 1);
                tbQLDH.setValueAt(rs.getString("TenSP"), i, 2);
                tbQLDH.setValueAt(rs.getString("NgayDat"), i, 3);
                tbQLDH.setValueAt(rs.getString("TrangThai"), i, 4);
                tbQLDH.setValueAt(rs.getInt("ThanhTien"), i, 5);
                i++;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    //cLICK CHUỘT CHỌN DỮ LIỆU TRÊN BẢNG

    //Load bảng
    private void loadbang(){
        xoatrangtable();
        try {
            //kết nối với MySQL
            cnpm_btl.ConnectMySQL con = new cnpm_btl.ConnectMySQL();
            ResultSet rs = con.getdata("hoadon");
            int i = 0;
            while(rs.next()){        
                tbQLDH.setValueAt(rs.getString("MaHD"), i, 0);
                tbQLDH.setValueAt(rs.getString("TenKH"), i, 1);
                tbQLDH.setValueAt(rs.getString("TenSP"), i, 2);
                tbQLDH.setValueAt(rs.getString("NgayDat"), i, 3);
                tbQLDH.setValueAt(rs.getString("TrangThai"), i, 4);
                tbQLDH.setValueAt(rs.getInt("ThanhTien"), i, 5);
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    //LÀM TRẮNG TEXTFIELD
    private void xoaTextField(){
        txtMaDH.setText("");
        txtTenKH.setText("");
        txtTenSP.setText("");
        txtNgayDat.setText("");
        txtTrangThai.setText("");
        txtThanhTien.setText("");
        txtSearch.setText("");
        loadbang();
        txtMaDH.setEnabled(true);
    }
    public void xoatrangtable(){
        for(int i = 0; i< tbQLDH.getRowCount(); i ++)
          for(int j = 0; j< tbQLDH.getColumnCount(); j ++) 
              tbQLDH.setValueAt("", i, j);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbQLDH;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
